#pragma once

#include <format>

#include <vulkan/vulkan.h>

template <typename T>
struct FmtVk {
  public:
    T value;
};

struct ApiVersion {
  public:
    uint32_t value;
};
static inline ApiVersion fmt_vk_api_version(uint32_t value) {
    return {value};
}

struct Version {
  public:
    uint32_t value;
};
static inline Version fmt_vk_version(uint32_t value) {
    return {value};
}

template <typename T>
static inline FmtVk<T> fmt_vk(T value) {
    return FmtVk<T> {value};
}

template <>
struct std::formatter<ApiVersion> {
    constexpr auto parse(std::format_parse_context& ctx) {
        return ctx.begin();
    }
    auto format(ApiVersion v, std::format_context& ctx) const {
        auto variant = VK_API_VERSION_VARIANT(v.value);
        auto major = VK_API_VERSION_MAJOR(v.value);
        auto minor = VK_API_VERSION_MINOR(v.value);
        auto patch = VK_API_VERSION_PATCH(v.value);
        return std::format_to(ctx.out(), "{}.{}.{}.{}", variant, major, minor, patch);
    }
};

template <>
struct std::formatter<Version> {
    constexpr auto parse(std::format_parse_context& ctx) {
        return ctx.begin();
    }
    auto format(Version v, std::format_context& ctx) const {
        auto major = VK_VERSION_MAJOR(v.value);
        auto minor = VK_VERSION_MINOR(v.value);
        auto patch = VK_VERSION_PATCH(v.value);
        return std::format_to(ctx.out(), "{}.{}.{}", major, minor, patch);
    }
};

#define ENUM_FMT_CASE(NAME)                                                                        \
    case NAME: return std::format_to(ctx.out(), #NAME)

#define ENUM_FMT_DEFAULT_CASE(TYPE, VALUE)                                                         \
    default: return std::format_to(ctx.out(), "(" #TYPE ")({})", (int32_t)VALUE)

template <>
struct std::formatter<FmtVk<VkResult>> {
    constexpr auto parse(std::format_parse_context& ctx) {
        return ctx.begin();
    }
    auto format(FmtVk<VkResult> v, std::format_context& ctx) const {
        switch (v.value) {
            ENUM_FMT_CASE(VK_SUCCESS);
            ENUM_FMT_CASE(VK_NOT_READY);
            ENUM_FMT_CASE(VK_TIMEOUT);
            ENUM_FMT_CASE(VK_EVENT_SET);
            ENUM_FMT_CASE(VK_EVENT_RESET);
            ENUM_FMT_CASE(VK_INCOMPLETE);
            ENUM_FMT_CASE(VK_ERROR_OUT_OF_HOST_MEMORY);
            ENUM_FMT_CASE(VK_ERROR_OUT_OF_DEVICE_MEMORY);
            ENUM_FMT_CASE(VK_ERROR_INITIALIZATION_FAILED);
            ENUM_FMT_CASE(VK_ERROR_DEVICE_LOST);
            ENUM_FMT_CASE(VK_ERROR_MEMORY_MAP_FAILED);
            ENUM_FMT_CASE(VK_ERROR_LAYER_NOT_PRESENT);
            ENUM_FMT_CASE(VK_ERROR_EXTENSION_NOT_PRESENT);
            ENUM_FMT_CASE(VK_ERROR_FEATURE_NOT_PRESENT);
            ENUM_FMT_CASE(VK_ERROR_INCOMPATIBLE_DRIVER);
            ENUM_FMT_CASE(VK_ERROR_TOO_MANY_OBJECTS);
            ENUM_FMT_CASE(VK_ERROR_FORMAT_NOT_SUPPORTED);
            ENUM_FMT_CASE(VK_ERROR_FRAGMENTED_POOL);
            ENUM_FMT_CASE(VK_ERROR_UNKNOWN);
            ENUM_FMT_CASE(VK_ERROR_OUT_OF_POOL_MEMORY);
            ENUM_FMT_CASE(VK_ERROR_INVALID_EXTERNAL_HANDLE);
            ENUM_FMT_CASE(VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS);
            ENUM_FMT_CASE(VK_ERROR_FRAGMENTATION);
            ENUM_FMT_CASE(VK_PIPELINE_COMPILE_REQUIRED);
            ENUM_FMT_CASE(VK_ERROR_NOT_PERMITTED);
            ENUM_FMT_CASE(VK_RESULT_MAX_ENUM);
        default:
            return std ::format_to(
                ctx.out(),
                "("
                "VkResult"
                ")({})",
                (int32_t)v.value);
        }
    }
};

template <>
struct std::formatter<FmtVk<VkPhysicalDeviceType>> {
    constexpr auto parse(std::format_parse_context& ctx) {
        return ctx.begin();
    }
    auto format(FmtVk<VkPhysicalDeviceType> v, std::format_context& ctx) const {
        switch (v.value) {
            ENUM_FMT_CASE(VK_PHYSICAL_DEVICE_TYPE_OTHER);
            ENUM_FMT_CASE(VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU);
            ENUM_FMT_CASE(VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU);
            ENUM_FMT_CASE(VK_PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU);
            ENUM_FMT_CASE(VK_PHYSICAL_DEVICE_TYPE_CPU);
            ENUM_FMT_CASE(VK_PHYSICAL_DEVICE_TYPE_MAX_ENUM);
            ENUM_FMT_DEFAULT_CASE(VkPhysicalDeviceType, v.value);
        }
    }
};

template <>
struct std::formatter<FmtVk<VkColorSpaceKHR>> {
    constexpr auto parse(std::format_parse_context& ctx) {
        return ctx.begin();
    }
    auto format(FmtVk<VkColorSpaceKHR> v, std::format_context& ctx) const {
        switch (v.value) {
            ENUM_FMT_CASE(VK_COLOR_SPACE_SRGB_NONLINEAR_KHR);
            ENUM_FMT_CASE(VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT);
            ENUM_FMT_CASE(VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT);
            ENUM_FMT_CASE(VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT);
            ENUM_FMT_CASE(VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT);
            ENUM_FMT_CASE(VK_COLOR_SPACE_BT709_LINEAR_EXT);
            ENUM_FMT_CASE(VK_COLOR_SPACE_BT709_NONLINEAR_EXT);
            ENUM_FMT_CASE(VK_COLOR_SPACE_BT2020_LINEAR_EXT);
            ENUM_FMT_CASE(VK_COLOR_SPACE_HDR10_ST2084_EXT);
            ENUM_FMT_CASE(VK_COLOR_SPACE_DOLBYVISION_EXT);
            ENUM_FMT_CASE(VK_COLOR_SPACE_HDR10_HLG_EXT);
            ENUM_FMT_CASE(VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT);
            ENUM_FMT_CASE(VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT);
            ENUM_FMT_CASE(VK_COLOR_SPACE_PASS_THROUGH_EXT);
            ENUM_FMT_CASE(VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT);
            ENUM_FMT_CASE(VK_COLOR_SPACE_DISPLAY_NATIVE_AMD);
            ENUM_FMT_CASE(VK_COLOR_SPACE_MAX_ENUM_KHR);
            ENUM_FMT_DEFAULT_CASE(VkColorSpaceKHR, v.value);
        }
    }
};

template <>
struct std::formatter<FmtVk<VkFormat>> {
    constexpr auto parse(std::format_parse_context& ctx) {
        return ctx.begin();
    }
    auto format(FmtVk<VkFormat> v, std::format_context& ctx) const {
        switch (v.value) {
            ENUM_FMT_CASE(VK_FORMAT_UNDEFINED);
            ENUM_FMT_CASE(VK_FORMAT_R4G4_UNORM_PACK8);
            ENUM_FMT_CASE(VK_FORMAT_R4G4B4A4_UNORM_PACK16);
            ENUM_FMT_CASE(VK_FORMAT_B4G4R4A4_UNORM_PACK16);
            ENUM_FMT_CASE(VK_FORMAT_R5G6B5_UNORM_PACK16);
            ENUM_FMT_CASE(VK_FORMAT_B5G6R5_UNORM_PACK16);
            ENUM_FMT_CASE(VK_FORMAT_R5G5B5A1_UNORM_PACK16);
            ENUM_FMT_CASE(VK_FORMAT_B5G5R5A1_UNORM_PACK16);
            ENUM_FMT_CASE(VK_FORMAT_A1R5G5B5_UNORM_PACK16);
            ENUM_FMT_CASE(VK_FORMAT_R8_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_R8_SNORM);
            ENUM_FMT_CASE(VK_FORMAT_R8_USCALED);
            ENUM_FMT_CASE(VK_FORMAT_R8_SSCALED);
            ENUM_FMT_CASE(VK_FORMAT_R8_UINT);
            ENUM_FMT_CASE(VK_FORMAT_R8_SINT);
            ENUM_FMT_CASE(VK_FORMAT_R8_SRGB);
            ENUM_FMT_CASE(VK_FORMAT_R8G8_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_R8G8_SNORM);
            ENUM_FMT_CASE(VK_FORMAT_R8G8_USCALED);
            ENUM_FMT_CASE(VK_FORMAT_R8G8_SSCALED);
            ENUM_FMT_CASE(VK_FORMAT_R8G8_UINT);
            ENUM_FMT_CASE(VK_FORMAT_R8G8_SINT);
            ENUM_FMT_CASE(VK_FORMAT_R8G8_SRGB);
            ENUM_FMT_CASE(VK_FORMAT_R8G8B8_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_R8G8B8_SNORM);
            ENUM_FMT_CASE(VK_FORMAT_R8G8B8_USCALED);
            ENUM_FMT_CASE(VK_FORMAT_R8G8B8_SSCALED);
            ENUM_FMT_CASE(VK_FORMAT_R8G8B8_UINT);
            ENUM_FMT_CASE(VK_FORMAT_R8G8B8_SINT);
            ENUM_FMT_CASE(VK_FORMAT_R8G8B8_SRGB);
            ENUM_FMT_CASE(VK_FORMAT_B8G8R8_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_B8G8R8_SNORM);
            ENUM_FMT_CASE(VK_FORMAT_B8G8R8_USCALED);
            ENUM_FMT_CASE(VK_FORMAT_B8G8R8_SSCALED);
            ENUM_FMT_CASE(VK_FORMAT_B8G8R8_UINT);
            ENUM_FMT_CASE(VK_FORMAT_B8G8R8_SINT);
            ENUM_FMT_CASE(VK_FORMAT_B8G8R8_SRGB);
            ENUM_FMT_CASE(VK_FORMAT_R8G8B8A8_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_R8G8B8A8_SNORM);
            ENUM_FMT_CASE(VK_FORMAT_R8G8B8A8_USCALED);
            ENUM_FMT_CASE(VK_FORMAT_R8G8B8A8_SSCALED);
            ENUM_FMT_CASE(VK_FORMAT_R8G8B8A8_UINT);
            ENUM_FMT_CASE(VK_FORMAT_R8G8B8A8_SINT);
            ENUM_FMT_CASE(VK_FORMAT_R8G8B8A8_SRGB);
            ENUM_FMT_CASE(VK_FORMAT_B8G8R8A8_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_B8G8R8A8_SNORM);
            ENUM_FMT_CASE(VK_FORMAT_B8G8R8A8_USCALED);
            ENUM_FMT_CASE(VK_FORMAT_B8G8R8A8_SSCALED);
            ENUM_FMT_CASE(VK_FORMAT_B8G8R8A8_UINT);
            ENUM_FMT_CASE(VK_FORMAT_B8G8R8A8_SINT);
            ENUM_FMT_CASE(VK_FORMAT_B8G8R8A8_SRGB);
            ENUM_FMT_CASE(VK_FORMAT_A8B8G8R8_UNORM_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_A8B8G8R8_SNORM_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_A8B8G8R8_USCALED_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_A8B8G8R8_SSCALED_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_A8B8G8R8_UINT_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_A8B8G8R8_SINT_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_A8B8G8R8_SRGB_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_A2R10G10B10_UNORM_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_A2R10G10B10_SNORM_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_A2R10G10B10_USCALED_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_A2R10G10B10_SSCALED_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_A2R10G10B10_UINT_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_A2R10G10B10_SINT_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_A2B10G10R10_UNORM_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_A2B10G10R10_SNORM_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_A2B10G10R10_USCALED_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_A2B10G10R10_SSCALED_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_A2B10G10R10_UINT_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_A2B10G10R10_SINT_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_R16_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_R16_SNORM);
            ENUM_FMT_CASE(VK_FORMAT_R16_USCALED);
            ENUM_FMT_CASE(VK_FORMAT_R16_SSCALED);
            ENUM_FMT_CASE(VK_FORMAT_R16_UINT);
            ENUM_FMT_CASE(VK_FORMAT_R16_SINT);
            ENUM_FMT_CASE(VK_FORMAT_R16_SFLOAT);
            ENUM_FMT_CASE(VK_FORMAT_R16G16_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_R16G16_SNORM);
            ENUM_FMT_CASE(VK_FORMAT_R16G16_USCALED);
            ENUM_FMT_CASE(VK_FORMAT_R16G16_SSCALED);
            ENUM_FMT_CASE(VK_FORMAT_R16G16_UINT);
            ENUM_FMT_CASE(VK_FORMAT_R16G16_SINT);
            ENUM_FMT_CASE(VK_FORMAT_R16G16_SFLOAT);
            ENUM_FMT_CASE(VK_FORMAT_R16G16B16_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_R16G16B16_SNORM);
            ENUM_FMT_CASE(VK_FORMAT_R16G16B16_USCALED);
            ENUM_FMT_CASE(VK_FORMAT_R16G16B16_SSCALED);
            ENUM_FMT_CASE(VK_FORMAT_R16G16B16_UINT);
            ENUM_FMT_CASE(VK_FORMAT_R16G16B16_SINT);
            ENUM_FMT_CASE(VK_FORMAT_R16G16B16_SFLOAT);
            ENUM_FMT_CASE(VK_FORMAT_R16G16B16A16_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_R16G16B16A16_SNORM);
            ENUM_FMT_CASE(VK_FORMAT_R16G16B16A16_USCALED);
            ENUM_FMT_CASE(VK_FORMAT_R16G16B16A16_SSCALED);
            ENUM_FMT_CASE(VK_FORMAT_R16G16B16A16_UINT);
            ENUM_FMT_CASE(VK_FORMAT_R16G16B16A16_SINT);
            ENUM_FMT_CASE(VK_FORMAT_R16G16B16A16_SFLOAT);
            ENUM_FMT_CASE(VK_FORMAT_R32_UINT);
            ENUM_FMT_CASE(VK_FORMAT_R32_SINT);
            ENUM_FMT_CASE(VK_FORMAT_R32_SFLOAT);
            ENUM_FMT_CASE(VK_FORMAT_R32G32_UINT);
            ENUM_FMT_CASE(VK_FORMAT_R32G32_SINT);
            ENUM_FMT_CASE(VK_FORMAT_R32G32_SFLOAT);
            ENUM_FMT_CASE(VK_FORMAT_R32G32B32_UINT);
            ENUM_FMT_CASE(VK_FORMAT_R32G32B32_SINT);
            ENUM_FMT_CASE(VK_FORMAT_R32G32B32_SFLOAT);
            ENUM_FMT_CASE(VK_FORMAT_R32G32B32A32_UINT);
            ENUM_FMT_CASE(VK_FORMAT_R32G32B32A32_SINT);
            ENUM_FMT_CASE(VK_FORMAT_R32G32B32A32_SFLOAT);
            ENUM_FMT_CASE(VK_FORMAT_R64_UINT);
            ENUM_FMT_CASE(VK_FORMAT_R64_SINT);
            ENUM_FMT_CASE(VK_FORMAT_R64_SFLOAT);
            ENUM_FMT_CASE(VK_FORMAT_R64G64_UINT);
            ENUM_FMT_CASE(VK_FORMAT_R64G64_SINT);
            ENUM_FMT_CASE(VK_FORMAT_R64G64_SFLOAT);
            ENUM_FMT_CASE(VK_FORMAT_R64G64B64_UINT);
            ENUM_FMT_CASE(VK_FORMAT_R64G64B64_SINT);
            ENUM_FMT_CASE(VK_FORMAT_R64G64B64_SFLOAT);
            ENUM_FMT_CASE(VK_FORMAT_R64G64B64A64_UINT);
            ENUM_FMT_CASE(VK_FORMAT_R64G64B64A64_SINT);
            ENUM_FMT_CASE(VK_FORMAT_R64G64B64A64_SFLOAT);
            ENUM_FMT_CASE(VK_FORMAT_B10G11R11_UFLOAT_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_E5B9G9R9_UFLOAT_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_D16_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_X8_D24_UNORM_PACK32);
            ENUM_FMT_CASE(VK_FORMAT_D32_SFLOAT);
            ENUM_FMT_CASE(VK_FORMAT_S8_UINT);
            ENUM_FMT_CASE(VK_FORMAT_D16_UNORM_S8_UINT);
            ENUM_FMT_CASE(VK_FORMAT_D24_UNORM_S8_UINT);
            ENUM_FMT_CASE(VK_FORMAT_D32_SFLOAT_S8_UINT);
            ENUM_FMT_CASE(VK_FORMAT_BC1_RGB_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_BC1_RGB_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_BC1_RGBA_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_BC1_RGBA_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_BC2_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_BC2_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_BC3_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_BC3_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_BC4_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_BC4_SNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_BC5_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_BC5_SNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_BC6H_UFLOAT_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_BC6H_SFLOAT_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_BC7_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_BC7_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_EAC_R11_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_EAC_R11_SNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_EAC_R11G11_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_EAC_R11G11_SNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_4x4_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_4x4_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_5x4_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_5x4_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_5x5_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_5x5_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_6x5_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_6x5_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_6x6_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_6x6_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_8x5_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_8x5_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_8x6_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_8x6_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_8x8_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_8x8_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_10x5_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_10x5_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_10x6_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_10x6_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_10x8_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_10x8_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_10x10_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_10x10_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_12x10_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_12x10_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_12x12_UNORM_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_12x12_SRGB_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_G8B8G8R8_422_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_B8G8R8G8_422_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_G8_B8R8_2PLANE_420_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_G8_B8R8_2PLANE_422_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_R10X6_UNORM_PACK16);
            ENUM_FMT_CASE(VK_FORMAT_R10X6G10X6_UNORM_2PACK16);
            ENUM_FMT_CASE(VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16);
            ENUM_FMT_CASE(VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16);
            ENUM_FMT_CASE(VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16);
            ENUM_FMT_CASE(VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16);
            ENUM_FMT_CASE(VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16);
            ENUM_FMT_CASE(VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16);
            ENUM_FMT_CASE(VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16);
            ENUM_FMT_CASE(VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16);
            ENUM_FMT_CASE(VK_FORMAT_R12X4_UNORM_PACK16);
            ENUM_FMT_CASE(VK_FORMAT_R12X4G12X4_UNORM_2PACK16);
            ENUM_FMT_CASE(VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16);
            ENUM_FMT_CASE(VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16);
            ENUM_FMT_CASE(VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16);
            ENUM_FMT_CASE(VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16);
            ENUM_FMT_CASE(VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16);
            ENUM_FMT_CASE(VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16);
            ENUM_FMT_CASE(VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16);
            ENUM_FMT_CASE(VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16);
            ENUM_FMT_CASE(VK_FORMAT_G16B16G16R16_422_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_B16G16R16G16_422_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_G16_B16R16_2PLANE_420_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_G16_B16R16_2PLANE_422_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_G8_B8R8_2PLANE_444_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16);
            ENUM_FMT_CASE(VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16);
            ENUM_FMT_CASE(VK_FORMAT_G16_B16R16_2PLANE_444_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_A4R4G4B4_UNORM_PACK16);
            ENUM_FMT_CASE(VK_FORMAT_A4B4G4R4_UNORM_PACK16);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK);
            ENUM_FMT_CASE(VK_FORMAT_A1B5G5R5_UNORM_PACK16);
            ENUM_FMT_CASE(VK_FORMAT_A8_UNORM);
            ENUM_FMT_CASE(VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG);
            ENUM_FMT_CASE(VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG);
            ENUM_FMT_CASE(VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG);
            ENUM_FMT_CASE(VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG);
            ENUM_FMT_CASE(VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG);
            ENUM_FMT_CASE(VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG);
            ENUM_FMT_CASE(VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG);
            ENUM_FMT_CASE(VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG);
            ENUM_FMT_CASE(VK_FORMAT_R8_BOOL_ARM);
            ENUM_FMT_CASE(VK_FORMAT_R16G16_SFIXED5_NV);
            ENUM_FMT_CASE(VK_FORMAT_R10X6_UINT_PACK16_ARM);
            ENUM_FMT_CASE(VK_FORMAT_R10X6G10X6_UINT_2PACK16_ARM);
            ENUM_FMT_CASE(VK_FORMAT_R10X6G10X6B10X6A10X6_UINT_4PACK16_ARM);
            ENUM_FMT_CASE(VK_FORMAT_R12X4_UINT_PACK16_ARM);
            ENUM_FMT_CASE(VK_FORMAT_R12X4G12X4_UINT_2PACK16_ARM);
            ENUM_FMT_CASE(VK_FORMAT_R12X4G12X4B12X4A12X4_UINT_4PACK16_ARM);
            ENUM_FMT_CASE(VK_FORMAT_R14X2_UINT_PACK16_ARM);
            ENUM_FMT_CASE(VK_FORMAT_R14X2G14X2_UINT_2PACK16_ARM);
            ENUM_FMT_CASE(VK_FORMAT_R14X2G14X2B14X2A14X2_UINT_4PACK16_ARM);
            ENUM_FMT_CASE(VK_FORMAT_R14X2_UNORM_PACK16_ARM);
            ENUM_FMT_CASE(VK_FORMAT_R14X2G14X2_UNORM_2PACK16_ARM);
            ENUM_FMT_CASE(VK_FORMAT_R14X2G14X2B14X2A14X2_UNORM_4PACK16_ARM);
            ENUM_FMT_CASE(VK_FORMAT_G14X2_B14X2R14X2_2PLANE_420_UNORM_3PACK16_ARM);
            ENUM_FMT_CASE(VK_FORMAT_G14X2_B14X2R14X2_2PLANE_422_UNORM_3PACK16_ARM);
            ENUM_FMT_CASE(VK_FORMAT_MAX_ENUM);
            ENUM_FMT_DEFAULT_CASE(VkFormat, v.value);
        }
    }
};

#undef ENUM_FMT_DEFAULT_CASE
#undef ENUM_FMT_CASE
